---

- name: Print how many RPM packages are installed
  hosts:
    - rocky
    - suse
  tasks:
    - name: Gather all RPM packages
      ansible.builtin.shell: rpm -qa | wc -l
      register: rpm_packages
      changed_when: false
    - name: Print all RPM packages using msg
      ansible.builtin.debug:
        msg: "{{ rpm_packages.stdout }}"
    - name: Print all RPM packages using var
      ansible.builtin.debug:
        var: rpm_packages.stdout

