---

- name: Install web server
  hosts: suse
  become: true
  tasks:
    - name: Install web server
      ansible.builtin.zypper:
        name: apache2
        state: present
        update_cache: true
    - name: Copy index.html
      ansible.builtin.copy:
        dest: /srv/www/htdocs/index.html
        mode: 0644
        content: |
          <!doctype html>
          <html>
            <head>
              <meta charset="utf-8">
              <title>Test</title>
            </head>
            <body>
              <h1> Apache web server running on {{ ansible_facts['hostname'] }}</h1>
            </body>
          </html>
    - name: Start web server
      ansible.builtin.service:
        name: apache2
        state: restarted
        enabled: true
