---

- name: Install Apache
  hosts: debian
  become: true
  tasks:
    - name: Install Apache
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: true
    - name: Copy index.html
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        mode: 0644
        content: |
          <!doctype html>
          <html>
            <head>
              <meta charset="utf-8">
              <title>Test</title>
            </head>
            <body>
              <h1> Apache web server running on {{ ansible_facts['hostname'] }}</h1>
            </body>
          </html>
    - name: Start Apache
      ansible.builtin.service:
        name: apache2
        state: restarted
        enabled: true
