---

- name: Install Chrony with package manager of hosts
  hosts: all 
  gather_facts: true
  tasks:

    - name: Include vars
      ansible.builtin.include_vars: >
        chrony02_{{ansible_distribution|lower|replace(" ", "-")}}.yml

    - name: Install chrony on Dall hosts
      ansible.builtin.package:
        name: "{{ chrony_package }}"
        state: present
        update_cache: true
    
    - name: Configure chrony
      ansible.builtin.template:
        src: chrony.conf.j2
        dest: "{{ chrony_confdir }}"
        mode: '0644'
      notify: restart chrony
      
  handlers:
    - name: restart chrony
      ansible.builtin.systemd:
        name: "{{ chrony_service }}"
        state: restarted
        enabled: yes

